; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ZZZ Bot"
#define MyAppVersion "1.11"
#define MyAppPublisher "Fly"
#define MyAppExeName "ZZZ Bot.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5A1F432A-3F15-4546-BE4E-76C38AE46154}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
OutputDir=C:\Users\PC\Documents\Playwright\ZZZ bot - Python\product
OutputBaseFilename=ZZZ Bot Installer
SetupIconFile=C:\Users\PC\Documents\Playwright\ZZZ bot - Python\images\Zhu Yuan02.ico
Compression=zip
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}";
Name: "startup"; Description: "{cm:AutoStartProgram,{#MyAppName}}"; GroupDescription: "{cm:AutoStartProgramGroupDescription}";

[Files]
Source: "C:\Users\PC\Documents\Playwright\ZZZ bot - Python\product\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\PC\Documents\Playwright\ZZZ bot - Python\product\dist\authentication data\*"; DestDir: "{app}\authentication data"; Flags: recursesubdirs createallsubdirs onlyifdoesntexist
Source: "C:\Users\PC\Documents\Playwright\ZZZ bot - Python\product\dist\output\*"; DestDir: "{app}\output"; Flags: recursesubdirs createallsubdirs onlyifdoesntexist
Source: "C:\Users\PC\Documents\Playwright\ZZZ bot - Python\product\dist\screenshot\*"; DestDir: "{app}\screenshot"; Flags: recursesubdirs createallsubdirs onlyifdoesntexist
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{autostartup}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: startup

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent unchecked

